"""abstract base model incorporated

Revision ID: 3fa3d7f96abb
Revises: 80ab3a78d0a2
Create Date: 2025-04-12 11:33:08.287729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3fa3d7f96abb'
down_revision: Union[str, None] = '80ab3a78d0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('api_keys', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.add_column('user_tokens', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user_tokens', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user_tokens', sa.Column('updated_at', sa.DateTime(timezone=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tokens', 'updated_at')
    op.drop_column('user_tokens', 'is_deleted')
    op.drop_column('user_tokens', 'is_active')
    op.alter_column('api_keys', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('api_keys', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
